version: 2.1

filter_main: &filter_main
  filters:
    branches:
      only:
        - main

orbs:
  semantic-release: trustedshops-public/semantic-release@6.0.0

executors:
  php:
    docker:
      - image: cimg/php:8.3.11
    resource_class: small

jobs:
  install:
    executor: php
    steps:
      - checkout
      - restore_cache:
          keys:
            # "composer.json" can be used if "composer.json"
            # is not committed to the repository.
            - composer-v2-{{ checksum "composer.lock" }}
            # fallback to using the latest cache if no exact match is found
            - composer-v2-
      - run: composer install -n --prefer-dist --ignore-platform-reqs
      - save_cache:
          key: composer-v2-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - persist_to_workspace:
          root: .
          paths:
            - .

  analyse:
    executor: php
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Codebase analysis with PHPStan
          command: |
            ./vendor/bin/phpstan analyse src --level=6
            ./vendor/bin/phpstan analyse tests --level=6
      - run:
          name: Codebase analysis with PHP-CS-Fixer
          command: |
            ./vendor/bin/php-cs-fixer fix src --dry-run --diff
            ./vendor/bin/php-cs-fixer fix tests --dry-run --diff

  test:
    executor: php
    steps:
      - attach_workspace:
          at: .
      - run: ./vendor/bin/phpunit tests

workflows:
  release:
    jobs:
      - install
      - analyse:
          requires:
            - install
      - test:
          requires:
            - analyse
      - semantic-release/with_changelog_github_config:
          name: semantic-release
          requires:
            - install
            - analyse
            - test
          <<: *filter_main
          context:
            - semantic-release
