services:
  trstdexampleintegration:
    class: TRSTDExampleIntegration
    factory: [Module, getInstanceByName]
    arguments:
      - "trstdexampleintegration"

  trstdexampleintegration.cot.cot_auth_repository:
    class: TRSTDExampleIntegration\COT\COTAuthRepository
    public: true

  trstdexampleintegration.form.type.client_configuration_text:
    class: 'TRSTDExampleIntegration\Form\ClientConfigurationFormType'
    parent: "form.type.translatable.aware"
    public: true
    tags:
      - { name: form.type }

  trstdexampleintegration.form.client_configuration_text_data_configuration:
    class: TRSTDExampleIntegration\Form\ClientConfigurationTextDataConfiguration
    public: true
    arguments: ["@prestashop.adapter.legacy.configuration"]

  trstdexampleintegration.form.client_configuration_text_form_data_provider:
    class: 'TRSTDExampleIntegration\Form\ClientConfigurationTextFormDataProvider'
    public: true
    arguments:
      - "@trstdexampleintegration.form.client_configuration_text_data_configuration"

  trstdexampleintegration.form.client_configuration_text_form_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    public: true
    arguments:
      - "@form.factory"
      - "@prestashop.core.hook.dispatcher"
      - "@trstdexampleintegration.form.client_configuration_text_form_data_provider"
      - 'TRSTDExampleIntegration\Form\ClientConfigurationFormType'
      - "ClientConfiguration"
